console.log("a + b =", a + b)
// console.log("a - b =", a - b)
// console.log("a * b =", a * b)
// console.log("a / b =", a / b)
// console.log("a ** b =", a ** b)
// console.log("b ** a =", b ** a)
// console.log("b % a =", a % b)